cupbyte/contact/urls.py
from django.urls import path
from . import views

app_name = "contact"
urlpatterns = [
    path('', views.contact, name="contact")
]

cupbyte/cupbyte/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("home.urls")),
    path('contact/', include("contact.urls")),
    path('admin/', admin.site.urls),
]

cupbyte/home/urls.py
from django.urls import path
from . import views
app_name = "home"
urlpatterns = [
    path('', views.index, name="index"),
]

cupbyte/contact/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
    name = models.CharField(max_length = 100)
    email = models.EmailField()
    comment = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add = True)

cupbyte/home/models.py
from django.db import models

# Create your models here.

cupbyte/contact/views.py
from django.shortcuts import render
from .models import Feedback
from .feedback_form import FeedbackForm
from django.http import HttpResponse

# Create your views here.
def contact(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Form Submitted")
    else:
        form = FeedbackForm()
    return render(request, 'contact/contact.html', {'form':form})

# def feedback(request):
    
#     return render(request, 'contact/contact.html', {'form':form})
        

cupbyte/home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    # render(request, 'index.html')
    # return HttpResponse("hello")
    return render(request, 'index.html')

cupbyte/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>CupByte</title>
        <!-- <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <script
            src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"
        ></script> -->
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Navbar</a>
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:index' %}"
                            >Home</a
                        >
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact:contact' %}"
                            >Contact</a
                        >
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input
                        class="form-control mr-sm-2"
                        type="search"
                        placeholder="Search"
                        aria-label="Search"
                    />
                    <button
                        class="btn btn-outline-success my-2 my-sm-0"
                        type="submit"
                    >
                        Search
                    </button>
                </form>
            </div>
        </nav>
        <div>
            {% block content %} {% endblock %}
        </div>
    </body>
</html>

cupbyte/templates/contact/contact.html
{% extends 'base.html' %} {% block content %}
<div>
    <form action="{% url 'contact:contact' %}" method="POST">
        {% csrf_token %} {{form}}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

cupbyte/templates/index.html
{% extends 'base.html' %} {% block content %}
<div>
    <p>Soumen</p>
</div>
{% endblock %}